// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dictor/jaeminbot/ent/command"
	"github.com/dictor/jaeminbot/ent/predicate"
	"github.com/dictor/jaeminbot/ent/resultlog"
)

// CommandUpdate is the builder for updating Command entities.
type CommandUpdate struct {
	config
	hooks    []Hook
	mutation *CommandMutation
}

// Where appends a list predicates to the CommandUpdate builder.
func (cu *CommandUpdate) Where(ps ...predicate.Command) *CommandUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetKeyword sets the "keyword" field.
func (cu *CommandUpdate) SetKeyword(s string) *CommandUpdate {
	cu.mutation.SetKeyword(s)
	return cu
}

// SetDetail sets the "detail" field.
func (cu *CommandUpdate) SetDetail(s string) *CommandUpdate {
	cu.mutation.SetDetail(s)
	return cu
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (cu *CommandUpdate) SetNillableDetail(s *string) *CommandUpdate {
	if s != nil {
		cu.SetDetail(*s)
	}
	return cu
}

// ClearDetail clears the value of the "detail" field.
func (cu *CommandUpdate) ClearDetail() *CommandUpdate {
	cu.mutation.ClearDetail()
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CommandUpdate) SetCreatedAt(t time.Time) *CommandUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CommandUpdate) SetNillableCreatedAt(t *time.Time) *CommandUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CommandUpdate) SetUpdatedAt(t time.Time) *CommandUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *CommandUpdate) SetNillableUpdatedAt(t *time.Time) *CommandUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// SetCreator sets the "creator" field.
func (cu *CommandUpdate) SetCreator(s string) *CommandUpdate {
	cu.mutation.SetCreator(s)
	return cu
}

// SetServer sets the "server" field.
func (cu *CommandUpdate) SetServer(s string) *CommandUpdate {
	cu.mutation.SetServer(s)
	return cu
}

// SetCode sets the "code" field.
func (cu *CommandUpdate) SetCode(s string) *CommandUpdate {
	cu.mutation.SetCode(s)
	return cu
}

// AddLogIDs adds the "logs" edge to the ResultLog entity by IDs.
func (cu *CommandUpdate) AddLogIDs(ids ...int) *CommandUpdate {
	cu.mutation.AddLogIDs(ids...)
	return cu
}

// AddLogs adds the "logs" edges to the ResultLog entity.
func (cu *CommandUpdate) AddLogs(r ...*ResultLog) *CommandUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddLogIDs(ids...)
}

// Mutation returns the CommandMutation object of the builder.
func (cu *CommandUpdate) Mutation() *CommandMutation {
	return cu.mutation
}

// ClearLogs clears all "logs" edges to the ResultLog entity.
func (cu *CommandUpdate) ClearLogs() *CommandUpdate {
	cu.mutation.ClearLogs()
	return cu
}

// RemoveLogIDs removes the "logs" edge to ResultLog entities by IDs.
func (cu *CommandUpdate) RemoveLogIDs(ids ...int) *CommandUpdate {
	cu.mutation.RemoveLogIDs(ids...)
	return cu
}

// RemoveLogs removes "logs" edges to ResultLog entities.
func (cu *CommandUpdate) RemoveLogs(r ...*ResultLog) *CommandUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommandUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommandMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommandUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommandUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommandUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CommandUpdate) check() error {
	if v, ok := cu.mutation.Keyword(); ok {
		if err := command.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf("ent: validator failed for field \"keyword\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Creator(); ok {
		if err := command.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf("ent: validator failed for field \"creator\": %w", err)}
		}
	}
	if v, ok := cu.mutation.Server(); ok {
		if err := command.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf("ent: validator failed for field \"server\": %w", err)}
		}
	}
	return nil
}

func (cu *CommandUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   command.Table,
			Columns: command.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: command.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Keyword(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldKeyword,
		})
	}
	if value, ok := cu.mutation.Detail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldDetail,
		})
	}
	if cu.mutation.DetailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: command.FieldDetail,
		})
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: command.FieldCreatedAt,
		})
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: command.FieldUpdatedAt,
		})
	}
	if value, ok := cu.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldCreator,
		})
	}
	if value, ok := cu.mutation.Server(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldServer,
		})
	}
	if value, ok := cu.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldCode,
		})
	}
	if cu.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedLogsIDs(); len(nodes) > 0 && !cu.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{command.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CommandUpdateOne is the builder for updating a single Command entity.
type CommandUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommandMutation
}

// SetKeyword sets the "keyword" field.
func (cuo *CommandUpdateOne) SetKeyword(s string) *CommandUpdateOne {
	cuo.mutation.SetKeyword(s)
	return cuo
}

// SetDetail sets the "detail" field.
func (cuo *CommandUpdateOne) SetDetail(s string) *CommandUpdateOne {
	cuo.mutation.SetDetail(s)
	return cuo
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (cuo *CommandUpdateOne) SetNillableDetail(s *string) *CommandUpdateOne {
	if s != nil {
		cuo.SetDetail(*s)
	}
	return cuo
}

// ClearDetail clears the value of the "detail" field.
func (cuo *CommandUpdateOne) ClearDetail() *CommandUpdateOne {
	cuo.mutation.ClearDetail()
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CommandUpdateOne) SetCreatedAt(t time.Time) *CommandUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CommandUpdateOne) SetNillableCreatedAt(t *time.Time) *CommandUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CommandUpdateOne) SetUpdatedAt(t time.Time) *CommandUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *CommandUpdateOne) SetNillableUpdatedAt(t *time.Time) *CommandUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// SetCreator sets the "creator" field.
func (cuo *CommandUpdateOne) SetCreator(s string) *CommandUpdateOne {
	cuo.mutation.SetCreator(s)
	return cuo
}

// SetServer sets the "server" field.
func (cuo *CommandUpdateOne) SetServer(s string) *CommandUpdateOne {
	cuo.mutation.SetServer(s)
	return cuo
}

// SetCode sets the "code" field.
func (cuo *CommandUpdateOne) SetCode(s string) *CommandUpdateOne {
	cuo.mutation.SetCode(s)
	return cuo
}

// AddLogIDs adds the "logs" edge to the ResultLog entity by IDs.
func (cuo *CommandUpdateOne) AddLogIDs(ids ...int) *CommandUpdateOne {
	cuo.mutation.AddLogIDs(ids...)
	return cuo
}

// AddLogs adds the "logs" edges to the ResultLog entity.
func (cuo *CommandUpdateOne) AddLogs(r ...*ResultLog) *CommandUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddLogIDs(ids...)
}

// Mutation returns the CommandMutation object of the builder.
func (cuo *CommandUpdateOne) Mutation() *CommandMutation {
	return cuo.mutation
}

// ClearLogs clears all "logs" edges to the ResultLog entity.
func (cuo *CommandUpdateOne) ClearLogs() *CommandUpdateOne {
	cuo.mutation.ClearLogs()
	return cuo
}

// RemoveLogIDs removes the "logs" edge to ResultLog entities by IDs.
func (cuo *CommandUpdateOne) RemoveLogIDs(ids ...int) *CommandUpdateOne {
	cuo.mutation.RemoveLogIDs(ids...)
	return cuo
}

// RemoveLogs removes "logs" edges to ResultLog entities.
func (cuo *CommandUpdateOne) RemoveLogs(r ...*ResultLog) *CommandUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveLogIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommandUpdateOne) Select(field string, fields ...string) *CommandUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Command entity.
func (cuo *CommandUpdateOne) Save(ctx context.Context) (*Command, error) {
	var (
		err  error
		node *Command
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommandMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommandUpdateOne) SaveX(ctx context.Context) *Command {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommandUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommandUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CommandUpdateOne) check() error {
	if v, ok := cuo.mutation.Keyword(); ok {
		if err := command.KeywordValidator(v); err != nil {
			return &ValidationError{Name: "keyword", err: fmt.Errorf("ent: validator failed for field \"keyword\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Creator(); ok {
		if err := command.CreatorValidator(v); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf("ent: validator failed for field \"creator\": %w", err)}
		}
	}
	if v, ok := cuo.mutation.Server(); ok {
		if err := command.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf("ent: validator failed for field \"server\": %w", err)}
		}
	}
	return nil
}

func (cuo *CommandUpdateOne) sqlSave(ctx context.Context) (_node *Command, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   command.Table,
			Columns: command.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: command.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Command.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, command.FieldID)
		for _, f := range fields {
			if !command.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != command.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Keyword(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldKeyword,
		})
	}
	if value, ok := cuo.mutation.Detail(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldDetail,
		})
	}
	if cuo.mutation.DetailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: command.FieldDetail,
		})
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: command.FieldCreatedAt,
		})
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: command.FieldUpdatedAt,
		})
	}
	if value, ok := cuo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldCreator,
		})
	}
	if value, ok := cuo.mutation.Server(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldServer,
		})
	}
	if value, ok := cuo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: command.FieldCode,
		})
	}
	if cuo.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedLogsIDs(); len(nodes) > 0 && !cuo.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   command.LogsTable,
			Columns: command.LogsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: resultlog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Command{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{command.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
