// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Command is the predicate function for command builders.
type Command func(*sql.Selector)

// ResultLog is the predicate function for resultlog builders.
type ResultLog func(*sql.Selector)
